[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "C", "B"] # Standard-Regeln + flake8-bugbear etc.
ignore = ["E501"] # wird von Black gehandhabt

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
